export enum StakenetPropertyEnum {
  erc20 = 'erc20',
  lockDurationInSeconds = 'lockDurationInSeconds',
  yieldPercentage = 'yieldPercentage',
  yieldDecimals = 'yieldDecimals',
  userHasStaked = 'userHasStaked',
  userStakedTimestamp = 'userStakedTimestamp',
  totalRewards = 'totalRewards',
  rewards = 'rewards',
  contractStakeLimit = 'contractStakeLimit',
  userStakeLimit = 'userStakeLimit',
  userMinimumStake = 'userMinimumStake',
  calculateMinStake = 'calculateMinStake',
  totalSupply = 'totalSupply',
  symbol = 'symbol',
  name = 'name',
  decimals = 'decimals',
  balanceOf = 'balanceOf',
  allowance = 'allowance',
  userData = 'userData',
}
